# Generated by Django 4.0 on 2021-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='passw',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
